import { test, expect } from '@playwright/test';
import { prisma } from '../lib/prisma';
import { v4 as uuidv4 } from 'uuid';
import bcrypt from 'bcryptjs';

test.describe('Prompt Management', () => {

    const testUsername = `mgruser_${Date.now()}`;
    const testPassword = 'Password123!';
    let testUserId: string;
    let testPromptId: string;

    test.beforeAll(async () => {
        // Setup valid user in DB
        const passwordHash = await bcrypt.hash(testPassword, 10);
        const user = await prisma.user.upsert({
            where: { username: testUsername },
            update: {},
            create: {
                id: uuidv4(),
                username: testUsername,
                email: `${testUsername}@example.com`,
                passwordHash: passwordHash,
                role: 'USER',
                settings: {
                    create: { id: uuidv4(), autoBackupEnabled: false }
                }
            }
        });
        testUserId = user.id;

        // Ensure global config
        await prisma.globalConfiguration.upsert({
            where: { id: 'GLOBAL' },
            update: { privatePromptsEnabled: true, registrationEnabled: true },
            create: { id: 'GLOBAL', privatePromptsEnabled: true, registrationEnabled: true }
        }).catch(() => { });
    });

    test.beforeEach(async ({ page }) => {
        // Seed a fresh prompt for each test to avoid interference
        const prompt = await prisma.prompt.create({
            data: {
                title: 'Management Test Prompt',
                description: 'Initial description',
                createdById: testUserId,
                isPrivate: false,
                isLocked: false,
                versions: {
                    create: {
                        versionNumber: 1,
                        content: 'Original Content with {{name}}',
                        createdById: testUserId,
                    }
                }
            }
        });
        testPromptId = prompt.id;

        // Log the user in
        await page.goto('/login');
        await page.getByPlaceholder('username').fill(testUsername);
        await page.locator('input[type="password"]').fill(testPassword);
        await page.getByRole('button', { name: 'Sign In', exact: false }).click();
        await page.waitForURL('**/');
    });

    test.afterEach(async () => {
        // Cleanup prompts
        await prisma.prompt.deleteMany({
            where: { createdById: testUserId }
        }).catch(() => { });
    });

    test.afterAll(async () => {
        // Cleanup user
        await prisma.user.delete({ where: { username: testUsername } }).catch(() => { });
    });

    test('Scenario 1: Metadata and Variable Interaction', async ({ page }) => {
        await page.goto(`/prompts/${testPromptId}`);

        // Check Metadata
        await expect(page.locator('h1.break-words')).toHaveText('Management Test Prompt');
        // Technical ID should be present (generated on creation usually, or check if null)
        // If technicalID is generated by trigger/middleware, wait for it
        const techId = page.locator('span[title="Technical ID"]');
        if (await techId.isVisible()) {
            await expect(techId).not.toBeEmpty();
        }

        // Variable Fill
        await expect(page.getByText('Fill Variables')).toBeVisible();
        await page.locator('textarea[id="name"]').fill('World');

        // Copy check (Success toast)
        await page.getByRole('button', { name: /Copy/i }).first().click();
        await expect(page.getByText(/Copied/i)).toBeVisible();
    });

    test('Scenario 2: Versioning and Restore', async ({ page }) => {
        await page.goto(`/prompts/${testPromptId}`);

        // Edit
        await page.locator('a[title="Edit"]').click();
        await page.waitForURL('**/edit');

        await page.locator('textarea[name="content"]').fill('Updated Content v2');
        await page.locator('textarea[name="changelog"]').fill('Test changelog');
        await page.locator('button[type="submit"]').click();

        // Should land back (strict path check to avoid matching /edit)
        await page.waitForURL(url => url.pathname === `/prompts/${testPromptId}`, { timeout: 15000 });

        // Scope to history card to avoid matching header on edit page if navigation failed
        const historyCard = page.locator('div.card', { hasText: /History/i });
        await expect(historyCard.getByText(/Version 2/i).first()).toBeVisible({ timeout: 10000 });
        await expect(page.locator('.bg-background.p-4.rounded-md.font-mono')).toContainText('Updated Content v2');

        // Restore Version 1
        const v1Row = page.locator('div.group').filter({ hasText: /Version 1/i }).first();
        await expect(v1Row).toBeVisible({ timeout: 10000 });
        await v1Row.locator('button').nth(1).click();

        // Confirm dialog
        const dialog = page.getByTestId('confirmation-dialog');
        await expect(dialog).toBeVisible({ timeout: 10000 });
        await dialog.getByRole('button').last().click();

        // Should create Version 3
        await expect(page.getByText('Version 3')).toBeVisible();
        await expect(page.locator('.bg-background.p-4.rounded-md.font-mono')).toContainText('Original Content');
    });

    test('Scenario 3: Visual Diff', async ({ page }) => {
        // Create an update first to have two versions
        await prisma.promptVersion.create({
            data: {
                promptId: testPromptId,
                versionNumber: 2,
                content: 'Original Content with changed suffix',
                createdById: testUserId,
            }
        });

        await page.goto(`/prompts/${testPromptId}`);

        // Click compare on v1 (since we are on v2)
        const v1Row = page.locator('.group.border', { hasText: 'Version 1' });
        await v1Row.locator('button[title*="Compare"]').click();

        // Check modal
        await expect(page.getByText('Compare Versions')).toBeVisible();
        await expect(page.locator('.overflow-auto .bg-green-100').first()).toBeVisible(); // additions
        await expect(page.locator('.overflow-auto .bg-red-100').first()).toBeVisible();   // deletions
    });

    test('Scenario 4: Lock/Unlock Toggle', async ({ page }) => {
        await page.goto(`/prompts/${testPromptId}`);

        // Lock it
        const lockBtn = page.locator('button[title*="Lock"]');
        await lockBtn.click();

        // Check if Locked (icon changes to Unlock or similar)
        // Wait for state change
        await expect(page.locator('button[title*="Unlock"]')).toBeVisible();

        // Verify Edit button is disabled
        // It has opacity-50 and pointer-events-none class on the <a> or is disabled
        const editBtn = page.locator('a[href*="/edit"], a[title*="Locked"]');
        await expect(editBtn).toHaveClass(/opacity-50/);

        // Unlock
        await page.locator('button[title*="Unlock"]').click();
        await expect(page.locator('button[title*="Lock"]')).toBeVisible();
        await expect(editBtn).not.toHaveClass(/opacity-50/);
    });

    test('Scenario 5: Private Prompt Restriction', async ({ page }) => {
        await page.goto(`/prompts/${testPromptId}`);

        // Make Private
        await page.locator('button[title*="Private"]').click();
        await expect(page.locator('.text-purple-600')).toBeVisible(); // Private badge color class

        // Sign out
        await page.goto('/'); // Go to dashboard
        // Click the user profile (bottom left usually)
        await page.locator('[data-testid="user-profile-trigger"]').click();
        await page.getByRole('button', { name: /Sign Out/i }).click();
        await page.waitForURL('**/login');

        // Now attempt to access the private prompt directly (as visitor)
        await page.goto(`/prompts/${testPromptId}`);
        // Middleware should redirect to login
        await page.waitForURL('**/login*');
    });

});
