"use client";

import { useTransition } from "react";
import { ArrowLeft, Info, Save } from "lucide-react";
import Link from "next/link";
import { updateWorkflowAction } from "@/actions/workflows";
import { useRouter } from "next/navigation";
import { SimplePrompt } from "./workflow/types";
import { useWorkflowSteps } from "./workflow/useWorkflowSteps";
import { StepList } from "./workflow/StepList";

export default function WorkflowEditor({ workflow, allPrompts }: { workflow: any, allPrompts: SimplePrompt[] }) {
    const {
        steps,
        addStep,
        removeStep,
        moveStep,
        updateMapping
    } = useWorkflowSteps(workflow.steps, allPrompts);

    const [isSaving, startTransition] = useTransition();
    const router = useRouter();

    // Save
    const handleSave = () => {
        startTransition(async () => {
            const formData = new FormData();
            formData.append("title", workflow.title);
            formData.append("description", workflow.description || "");

            const apiSteps = steps.map((s, i) => ({
                promptId: s.promptId,
                order: i,
                inputMappings: s.inputMappings
            }));

            formData.append("steps", JSON.stringify(apiSteps));

            await updateWorkflowAction(workflow.id, formData);
            router.refresh();
        });
    };

    return (
        <div className="space-y-6">
            {/* Header */}
            <div className="flex justify-between items-center bg-surface p-4 rounded-lg border border-border sticky top-4 z-10 shadow-sm">
                <div className="flex items-center gap-4">
                    <Link href="/workflows" className="btn btn-ghost btn-sm btn-square"><ArrowLeft /></Link>
                    <div>
                        <h1 className="text-xl font-bold">{workflow.title}</h1>
                        <p className="text-xs text-muted-foreground">{steps.length} Steps</p>
                    </div>
                </div>
                <button onClick={handleSave} className="btn btn-primary" disabled={isSaving}>
                    <Save size={18} className="mr-2" />
                    {isSaving ? "Saving..." : "Save Workflow"}
                </button>
            </div>

            {/* Workflow Builder Grid */}
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                {/* Left: Step List */}
                <StepList
                    steps={steps}
                    allPrompts={allPrompts}
                    onAddStep={addStep}
                    onMoveUp={(i) => moveStep(i, 'up')}
                    onMoveDown={(i) => moveStep(i, 'down')}
                    onRemove={removeStep}
                    onUpdateMapping={updateMapping}
                />

                {/* Right: Sidebar / Info */}
                <div className="lg:col-span-1">
                    <div className="card p-5 bg-surface border border-border sticky top-24">
                        <h3 className="font-bold mb-4 flex items-center gap-2">
                            <Info size={16} /> Workflow Logic
                        </h3>
                        <div className="text-sm text-muted-foreground space-y-4">
                            <p>
                                <strong>1. Sequence:</strong> Prompts run in order from top to bottom.
                            </p>
                            <p>
                                <strong>2. Variables:</strong> Each prompt can receive input from:
                            </p>
                            <ul className="list-disc list-inside ml-2 space-y-1">
                                <li><strong>User Input:</strong> Values you provide when you start the run.</li>
                                <li><strong>Step Output:</strong> The result generated by a previous step.</li>
                            </ul>
                            <div className="alert alert-info py-2 text-xs mt-4">
                                <Info size={14} /> Reordering steps may break mappings. Check your settings after moving items!
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
